# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIIndicatorConfig.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from org.zqb.stock.ui.IndicatorConfig.IndCfgTableWidget import IndCfgTableWidget

class UIIndicatorConfig(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1169, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBoxReport = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxReport.setObjectName("groupBoxReport")
        self.gridLayoutReport = QtWidgets.QGridLayout(self.groupBoxReport)
        self.gridLayoutReport.setObjectName("gridLayoutReport")
        self.tableWidgetReport = IndCfgTableWidget(self.groupBoxReport)
        self.tableWidgetReport.setObjectName("tableWidgetReport")
        self.tableWidgetReport.setColumnCount(4)
        self.tableWidgetReport.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReport.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReport.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReport.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetReport.setHorizontalHeaderItem(3, item)
        self.gridLayoutReport.addWidget(self.tableWidgetReport, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxReport, 0, 1, 1, 1)
        self.groupBoxProfit = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxProfit.setObjectName("groupBoxProfit")
        self.gridLayoutProfit = QtWidgets.QGridLayout(self.groupBoxProfit)
        self.gridLayoutProfit.setObjectName("gridLayoutProfit")
        self.tableWidgetProfit = IndCfgTableWidget(self.groupBoxProfit)
        self.tableWidgetProfit.setObjectName("tableWidgetProfit")
        self.tableWidgetProfit.setColumnCount(4)
        self.tableWidgetProfit.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProfit.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProfit.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProfit.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetProfit.setHorizontalHeaderItem(3, item)
        self.gridLayoutProfit.addWidget(self.tableWidgetProfit, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxProfit, 0, 2, 1, 1)
        self.groupBoxBasics = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxBasics.setObjectName("groupBoxBasics")
        self.gridLayoutBasics = QtWidgets.QGridLayout(self.groupBoxBasics)
        self.gridLayoutBasics.setObjectName("gridLayoutBasics")
        self.tableWidgetBasics = IndCfgTableWidget(self.groupBoxBasics)
        self.tableWidgetBasics.setRowCount(0)
        self.tableWidgetBasics.setColumnCount(4)
        self.tableWidgetBasics.setObjectName("tableWidgetBasics")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBasics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBasics.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBasics.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBasics.setHorizontalHeaderItem(3, item)
        self.gridLayoutBasics.addWidget(self.tableWidgetBasics, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxBasics, 0, 0, 1, 1)
        self.groupBoxDebt = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDebt.setObjectName("groupBoxDebt")
        self.gridLayoutDebt = QtWidgets.QGridLayout(self.groupBoxDebt)
        self.gridLayoutDebt.setObjectName("gridLayoutDebt")
        self.tableWidgetDebt = IndCfgTableWidget(self.groupBoxDebt)
        self.tableWidgetDebt.setObjectName("tableWidgetDebt")
        self.tableWidgetDebt.setColumnCount(4)
        self.tableWidgetDebt.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDebt.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDebt.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDebt.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDebt.setHorizontalHeaderItem(3, item)
        self.gridLayoutDebt.addWidget(self.tableWidgetDebt, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxDebt, 1, 2, 1, 1)
        self.groupBoxGrowth = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxGrowth.setObjectName("groupBoxGrowth")
        self.gridLayoutGrowth = QtWidgets.QGridLayout(self.groupBoxGrowth)
        self.gridLayoutGrowth.setObjectName("gridLayoutGrowth")
        self.tableWidgetGrowth = IndCfgTableWidget(self.groupBoxGrowth)
        self.tableWidgetGrowth.setObjectName("tableWidgetGrowth")
        self.tableWidgetGrowth.setColumnCount(4)
        self.tableWidgetGrowth.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetGrowth.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetGrowth.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetGrowth.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetGrowth.setHorizontalHeaderItem(3, item)
        self.gridLayoutGrowth.addWidget(self.tableWidgetGrowth, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxGrowth, 1, 1, 1, 1)
        self.groupBoxCash = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxCash.setObjectName("groupBoxCash")
        self.gridLayoutCash = QtWidgets.QGridLayout(self.groupBoxCash)
        self.gridLayoutCash.setObjectName("gridLayoutCash")
        self.tableWidgetCash = IndCfgTableWidget(self.groupBoxCash)
        self.tableWidgetCash.setObjectName("tableWidgetCash")
        self.tableWidgetCash.setColumnCount(4)
        self.tableWidgetCash.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCash.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCash.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCash.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetCash.setHorizontalHeaderItem(3, item)
        self.gridLayoutCash.addWidget(self.tableWidgetCash, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxCash, 2, 0, 1, 1)
        self.groupBoxOper = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxOper.setObjectName("groupBoxOper")
        self.gridLayoutOper = QtWidgets.QGridLayout(self.groupBoxOper)
        self.gridLayoutOper.setObjectName("gridLayoutOper")
        self.tableWidgetOper = IndCfgTableWidget(self.groupBoxOper)
        self.tableWidgetOper.setObjectName("tableWidgetOper")
        self.tableWidgetOper.setColumnCount(4)
        self.tableWidgetOper.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOper.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOper.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOper.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetOper.setHorizontalHeaderItem(3, item)
        self.gridLayoutOper.addWidget(self.tableWidgetOper, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBoxOper, 1, 0, 1, 1)
        self.widgetButtons = QtWidgets.QWidget(self.centralwidget)
        self.widgetButtons.setObjectName("widgetButtons")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetButtons)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.widgetButtons)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2.addWidget(self.widget_3, 0, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widgetButtons)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.widgetButtons)
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonOK = QtWidgets.QPushButton(self.widget_4)
        self.pushButtonOK.setObjectName("pushButtonOK")
        self.gridLayout_5.addWidget(self.pushButtonOK, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 0, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.widget)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButtonCancel = QtWidgets.QPushButton(self.widget_5)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout_6.addWidget(self.pushButtonCancel, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_5, 1, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_3.addWidget(self.widget_6, 2, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.widget)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_3.addWidget(self.widget_7, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widgetButtons, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButtonOK.clicked.connect(MainWindow.OK)
        self.pushButtonCancel.clicked.connect(MainWindow.cancel)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "选择指标"))
        self.groupBoxReport.setTitle(_translate("MainWindow", "业绩指标"))
        item = self.tableWidgetReport.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "代码"))
        item = self.tableWidgetReport.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidgetReport.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidgetReport.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "排序"))
        self.groupBoxProfit.setTitle(_translate("MainWindow", "盈利指标"))
        item = self.tableWidgetProfit.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "代码"))
        item = self.tableWidgetProfit.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidgetProfit.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidgetProfit.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "排序"))
        self.groupBoxBasics.setTitle(_translate("MainWindow", "基本指标"))
        item = self.tableWidgetBasics.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "代码"))
        item = self.tableWidgetBasics.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidgetBasics.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidgetBasics.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "排序"))
        self.groupBoxDebt.setTitle(_translate("MainWindow", "偿债指标"))
        item = self.tableWidgetDebt.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "代码"))
        item = self.tableWidgetDebt.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidgetDebt.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidgetDebt.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "排序"))
        self.groupBoxGrowth.setTitle(_translate("MainWindow", "成长指标"))
        item = self.tableWidgetGrowth.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "代码"))
        item = self.tableWidgetGrowth.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidgetGrowth.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidgetGrowth.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "排序"))
        self.groupBoxCash.setTitle(_translate("MainWindow", "现金流量"))
        item = self.tableWidgetCash.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "代码"))
        item = self.tableWidgetCash.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidgetCash.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidgetCash.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "排序"))
        self.groupBoxOper.setTitle(_translate("MainWindow", "营运指标"))
        item = self.tableWidgetOper.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "代码"))
        item = self.tableWidgetOper.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "名称"))
        item = self.tableWidgetOper.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "选择"))
        item = self.tableWidgetOper.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "排序"))
        self.pushButtonOK.setText(_translate("MainWindow", "OK"))
        self.pushButtonCancel.setText(_translate("MainWindow", "Cancel"))

